language: java
#############################
# Required for running docker
sudo: required
services:
  - docker
#############################
addons:
  sonarcloud:
    organization: "joseyustiz-github"
    token:
      secure: $SONAR_TOKEN
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  # other script steps might be done before running the actual analysis
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - ./gradlew build sonarqube docker #jacocoMerge sonarqube -Dsonar.jacoco.reportPaths=${TRAVIS_BUILD_DIR}/jacoco/allTestCoverage.exec
#  - sonar-scanner -Dsonar.jacoco.reportPaths=${TRAVIS_BUILD_DIR}/jacoco/allTestCoverage.exec
notifications:
  email: false #disabling email notification