spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./build/h2db/db/account;DB_CLOSE_DELAY=-1
    username: sa
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
  h2:
    console:
      enabled: true